### ISSUE TITLE
Couple comments

### ISSUE THREAD

**Issue by Leseratte10** [CLF78/OpenPayload#1]
Hi @CLF78, 

I've just skimmed the whole code in the repository, and wanted to answer some of the questions in the comments as well as ask some questions myself. 

So here's my answers to your questions:

- ConnectionMatrix.cpp, line 30, "Why is the interrupt lock needed"? - Bean said that this step was necessary when we implemented it, because he concluded that it was theoretically possible for the player to disconnect while this function is running which could cause another thread to reset the stpMatchCnt and result in a null pointer crash. 
- MatchCommand.cpp, line 32, "Why can't we just find the lowest AID" - I don't think there's a particular reason why we're going through the entire loop, no. With the current implementation it would take the client with the highest AID, though, and your suggestion would be using the lowest AID. I'm not sure if this would result in issues when one client is on the Wiimmfi payload and another is on the OpenPayload. If you do want to skip the additional loop iterations with a "break" I'd suggest looping through the list in reverse order so both will end up with the same client (highest AID).
- MatchCommand.cpp, line 55, "Why are we copying to the temp node?" - No idea, the original game does it as well I believe and if I remember correctly it fixed some weird bugs we had, but I don't remember the specifics. 

- Natneg.cpp, line 129, "Why isn't PostProcessConnection called" - the function `StoreConnectionAndInfo` or as the Wiimmfi payload calls it `FinaliseGT2Connection` is not used for "normal" p2p connections that went through NATNEG, it's only used when we're building a connection ourselves. I don't remember the specifics from this case, but it was probably weird side effects in the "official" functions like PostProcessConnection so we only did the absolute minimum to get the connection working. 
- Natneg.cpp, line 152, "What's the difference between wait1 and wait2" -  there isn't really one anymore. They're just for two seperate error states (wrong state vs. peer not found), and when we were developing / debugging this we had different timeouts and error handlings for both that were later scrapped. 
- Natneg.cpp, line 174/175; and 279/280: All the states in the switch statement are the different states the client can get stuck doing NATNEG or initiating a new connection. If the client is stuck in one of these states for whatever reason, still trying to connect to that PID, we cancel the connection. The PID check is so that we only cancel when the player is stuck doing a connection to that particular other player, and not when the game has progressed on and is doing NATNEG with someone else already
- Natneg.cpp, line 203, "Why isn't the connection rejected" - that's probably a bug. But in practice the game should never run into this branch anyways since our connections are only between existing players (not when a new player joins) so the list should never be full anyways.
- Natneg.cpp, line 240, "Why the profileID check with <=" - do you mean why do we use <= as opposed to <, or why is there a check at all? This code is for a desync - when building a p2p connection you have one peer that's opening the connection attempt and another that's accepting it. If during a desync both clients were to open a new connection, they would be unable to connect. So we made it that the player with a smaller PID immediately retries and the player with a larger PID waits 150 ticks. 
- Natneg.cpp, line 388, "What's the point of RecoverSynAckTimeout" - not quite sure about that, MrBean wrote that function together with a couple other stability fixes. I believe it's some kind of weird state issue where one client thinks it's already connecting to a peer (and waiting for a response) but the other side doesn't know about that; but if you want to know more details you'd need to ask Bean.
- Natneg.cpp, line 435, "Why is the time backed up" - probably so the timers used by the game for error handling and stuff still refer to the last point in time when the game's original code sent the packets, not the mod; but for more details you'd need to ask Bean as with the previous question.

- Reporting.cpp, line 138, "Why hash twice"? - sure, we could make it so that it sets lap count to 3 and speed to 0, then hashes the KMP, then send that to Wiimmfi - but if Wiimmfi only knows about the track with a modded lap count it can't do anything with this information. The point of that was so that Wiimmfi (which only has a list of checksums at the moment) can find the track, either with the original KMP or with a cleaned KMP.
- Reporting.cpp, line 225, "Is the lock necessary?" - Yes, it is, because the code is technically running on the wrong thread here. Without the lock, if you were to disconnect at just the right (or wrong) moment, it's possible that the pointer is not null when it's checked but will be set to 0 before it's used, causing a crash.
- Reporting.cpp, line 292, "why not use existing strings" - good question - I have no idea. In practice these wouldn't even really be needed at all since it's already sending the internal ID anyways and Wiimmfi could just find the matching state string from its own list. I'll take a closer look some time.
- Reporting.cpp, line 359, reporting the first four PIDs - yes, this should probably be removed. Wiimm requested that I add that a long time ago when he was debugging issues with Wiimmfi's room detection (which still isn't working 100% like we want it to) and to detect room split issues. When the new room detection model on Wiimmfi is finally finished, quite a bit of these small weird reporting things will be removed from the payload.

- Status.cpp, line 32, "why the scrambling" - Wiimm wrote that code so I'm not 100% sure, but I don't think it's a scrambling to hide stuff, it's shifting the characters around so they're in the proper offsets for the substitution so only letters and numbers and stuff are getting substituted

And here's a couple questions / general annotations about your code that I had while skimming through it:

- The console type we're sending in Auth.cpp doesn't really have a reason other than statistics anymore (how many people are on a Wii, WiiU, Dolphin, WiiMini), same probably goes for the region. Though your implementation is slightly wrong, your comment states that you're acting like a PAL Wii but in fact you're acting like a PAL Dolphin. I don't see the harm in sending that information - most of it Wiimmfi could already guess anyways from parsing the console serial number string so I'd appreciate if your payload would also send correct data here. Though, if you really don't want to send that data maybe we can work something out to have Wiimmfi ignore console type reports from OpenPayload to not mess with these statistics. 
- Which brings me to the next point - your payload is currently identifying as "LE-CODE GCT", which I really don't like. We have never ever treated any patcher different from the others unless there's a technical reason to do so (like, something is broken in one patcher that needs to be fixed and we need to temporarily lock out users of a certain patcher) - so I don't see the need for your payload to misidentify itself as another, especially not with how different they are. If we ever see some weird behaviour on Wiimmfi that only occurs with some clients, we'd like to know what patcher they're using - so, would you mind changing that string to "OpenPayload by CLF" or something like that?
- The used IOS that's also sent to Wiimmfi is not really needed, correct. We added that a long time ago when there was some kind of issue that was IOS-dependant (so it worked on some IOSes and failed on others) and we needed to know which clients were using which IOSes. This value has only ever ended up in debug logs and wasn't even interpreted by Wiimmfi, so instead of sending potentially-wrong data you could just remove the parameter entirely, it's not getting validated by Wiimmfi and it's unlikely that it ever will.
- In Reporting.cpp in `ReportSelectInfo`, the Wiimmfi payload is reporting `packet->engineClass & 0x0F` while your payload is reporting `packet->engineClass`, that could cause issues when your payload is combined with other mods like LE-CODE. Would you mind changing that as well?

**Comment by CLF78** [comment]
Hello, i'm writing this comment just to provide closure to whoever will read this (the topic was discussed over on Discord):
- All the authentication issues have been resolved, so now OpenPayload reports the correct info to the server.
- The engine class reporting will not be fixed, as it's up to mods to modify the code to suit their own needs.
- Other issues such as the scrambling not working properly and a crash due to an incorrect symbol were fixed along the way.
- Thanks for answering the questions. I will be removing the corresponding comments shortly.
